export const flags = {
   ad: {url: {small: "https://flagcdn.com/64x48/ad.png", large: "https://flagcdn.com/120x90/ad.png"}, name: "Andorra"},
   ae: {url: {small: "https://flagcdn.com/64x48/ae.png", large: "https://flagcdn.com/120x90/ae.png"}, name: "United Arab Emirates"},
   af: {url: {small: "https://flagcdn.com/64x48/af.png", large: "https://flagcdn.com/120x90/af.png"}, name: "Afghanistan"},
   ag: {url: {small: "https://flagcdn.com/64x48/ag.png", large: "https://flagcdn.com/120x90/ag.png"}, name: "Antigua and Barbuda"},
   ai: {url: {small: "https://flagcdn.com/64x48/ai.png", large: "https://flagcdn.com/120x90/ai.png"}, name: "Anguilla"},
   al: {url: {small: "https://flagcdn.com/64x48/al.png", large: "https://flagcdn.com/120x90/al.png"}, name: "Albania"},
   am: {url: {small: "https://flagcdn.com/64x48/am.png", large: "https://flagcdn.com/120x90/am.png"}, name: "Armenia"},
   ao: {url: {small: "https://flagcdn.com/64x48/ao.png", large: "https://flagcdn.com/120x90/ao.png"}, name: "Angola"},
   aq: {url: {small: "https://flagcdn.com/64x48/aq.png", large: "https://flagcdn.com/120x90/aq.png"}, name: "Antarctica"},
   ar: {url: {small: "https://flagcdn.com/64x48/ar.png", large: "https://flagcdn.com/120x90/ar.png"}, name: "Argentina"},
   as: {url: {small: "https://flagcdn.com/64x48/as.png", large: "https://flagcdn.com/120x90/as.png"}, name: "American Samoa"},
   at: {url: {small: "https://flagcdn.com/64x48/at.png", large: "https://flagcdn.com/120x90/at.png"}, name: "Austria"},
   au: {url: {small: "https://flagcdn.com/64x48/au.png", large: "https://flagcdn.com/120x90/au.png"}, name: "Australia"},
   aw: {url: {small: "https://flagcdn.com/64x48/aw.png", large: "https://flagcdn.com/120x90/aw.png"}, name: "Aruba"},
   ax: {url: {small: "https://flagcdn.com/64x48/ax.png", large: "https://flagcdn.com/120x90/ax.png"}, name: "Åland Islands"},
   az: {url: {small: "https://flagcdn.com/64x48/az.png", large: "https://flagcdn.com/120x90/az.png"}, name: "Azerbaijan"},
   ba: {url: {small: "https://flagcdn.com/64x48/ba.png", large: "https://flagcdn.com/120x90/ba.png"}, name: "Bosnia and Herzegovina"},
   bb: {url: {small: "https://flagcdn.com/64x48/bb.png", large: "https://flagcdn.com/120x90/bb.png"}, name: "Barbados"},
   bd: {url: {small: "https://flagcdn.com/64x48/bd.png", large: "https://flagcdn.com/120x90/bd.png"}, name: "Bangladesh"},
   be: {url: {small: "https://flagcdn.com/64x48/be.png", large: "https://flagcdn.com/120x90/be.png"}, name: "Belgium"},
   bf: {url: {small: "https://flagcdn.com/64x48/bf.png", large: "https://flagcdn.com/120x90/bf.png"}, name: "Burkina Faso"},
   bg: {url: {small: "https://flagcdn.com/64x48/bg.png", large: "https://flagcdn.com/120x90/bg.png"}, name: "Bulgaria"},
   bh: {url: {small: "https://flagcdn.com/64x48/bh.png", large: "https://flagcdn.com/120x90/bh.png"}, name: "Bahrain"},
   bi: {url: {small: "https://flagcdn.com/64x48/bi.png", large: "https://flagcdn.com/120x90/bi.png"}, name: "Burundi"},
   bj: {url: {small: "https://flagcdn.com/64x48/bj.png", large: "https://flagcdn.com/120x90/bj.png"}, name: "Benin"},
   bl: {url: {small: "https://flagcdn.com/64x48/bl.png", large: "https://flagcdn.com/120x90/bl.png"}, name: "Saint Barthélemy"},
   bm: {url: {small: "https://flagcdn.com/64x48/bm.png", large: "https://flagcdn.com/120x90/bm.png"}, name: "Bermuda"},
   bn: {url: {small: "https://flagcdn.com/64x48/bn.png", large: "https://flagcdn.com/120x90/bn.png"}, name: "Brunei"},
   bo: {url: {small: "https://flagcdn.com/64x48/bo.png", large: "https://flagcdn.com/120x90/bo.png"}, name: "Bolivia"},
   bq: {url: {small: "https://flagcdn.com/64x48/bq.png", large: "https://flagcdn.com/120x90/bq.png"}, name: "Caribbean Netherlands"},
   br: {url: {small: "https://flagcdn.com/64x48/br.png", large: "https://flagcdn.com/120x90/br.png"}, name: "Brazil"},
   bs: {url: {small: "https://flagcdn.com/64x48/bs.png", large: "https://flagcdn.com/120x90/bs.png"}, name: "Bahamas"},
   bt: {url: {small: "https://flagcdn.com/64x48/bt.png", large: "https://flagcdn.com/120x90/bt.png"}, name: "Bhutan"},
   bv: {url: {small: "https://flagcdn.com/64x48/bv.png", large: "https://flagcdn.com/120x90/bv.png"}, name: "Bouvet Island"},
   bw: {url: {small: "https://flagcdn.com/64x48/bw.png", large: "https://flagcdn.com/120x90/bw.png"}, name: "Botswana"},
   by: {url: {small: "https://flagcdn.com/64x48/by.png", large: "https://flagcdn.com/120x90/by.png"}, name: "Belarus"},
   bz: {url: {small: "https://flagcdn.com/64x48/bz.png", large: "https://flagcdn.com/120x90/bz.png"}, name: "Belize"},
   ca: {url: {small: "https://flagcdn.com/64x48/ca.png", large: "https://flagcdn.com/120x90/ca.png"}, name: "Canada"},
   cc: {url: {small: "https://flagcdn.com/64x48/cc.png", large: "https://flagcdn.com/120x90/cc.png"}, name: "Cocos (Keeling) Islands"},
   cd: {url: {small: "https://flagcdn.com/64x48/cd.png", large: "https://flagcdn.com/120x90/cd.png"}, name: "DR Congo"},
   cf: {url: {small: "https://flagcdn.com/64x48/cf.png", large: "https://flagcdn.com/120x90/cf.png"}, name: "Central African Republic"},
   cg: {url: {small: "https://flagcdn.com/64x48/cg.png", large: "https://flagcdn.com/120x90/cg.png"}, name: "Republic of the Congo"},
   ch: {url: {small: "https://flagcdn.com/64x48/ch.png", large: "https://flagcdn.com/120x90/ch.png"}, name: "Switzerland"},
   ci: {url: {small: "https://flagcdn.com/64x48/ci.png", large: "https://flagcdn.com/120x90/ci.png"}, name: "Côte d'Ivoire (Ivory Coast)"},
   ck: {url: {small: "https://flagcdn.com/64x48/ck.png", large: "https://flagcdn.com/120x90/ck.png"}, name: "Cook Islands"},
   cl: {url: {small: "https://flagcdn.com/64x48/cl.png", large: "https://flagcdn.com/120x90/cl.png"}, name: "Chile"},
   cm: {url: {small: "https://flagcdn.com/64x48/cm.png", large: "https://flagcdn.com/120x90/cm.png"}, name: "Cameroon"},
   cn: {url: {small: "https://flagcdn.com/64x48/cn.png", large: "https://flagcdn.com/120x90/cn.png"}, name: "China"},
   co: {url: {small: "https://flagcdn.com/64x48/co.png", large: "https://flagcdn.com/120x90/co.png"}, name: "Colombia"},
   cr: {url: {small: "https://flagcdn.com/64x48/cr.png", large: "https://flagcdn.com/120x90/cr.png"}, name: "Costa Rica"},
   cu: {url: {small: "https://flagcdn.com/64x48/cu.png", large: "https://flagcdn.com/120x90/cu.png"}, name: "Cuba"},
   cv: {url: {small: "https://flagcdn.com/64x48/cv.png", large: "https://flagcdn.com/120x90/cv.png"}, name: "Cape Verde"},
   cw: {url: {small: "https://flagcdn.com/64x48/cw.png", large: "https://flagcdn.com/120x90/cw.png"}, name: "Curaçao"},
   cx: {url: {small: "https://flagcdn.com/64x48/cx.png", large: "https://flagcdn.com/120x90/cx.png"}, name: "Christmas Island"},
   cy: {url: {small: "https://flagcdn.com/64x48/cy.png", large: "https://flagcdn.com/120x90/cy.png"}, name: "Cyprus"},
   cz: {url: {small: "https://flagcdn.com/64x48/cz.png", large: "https://flagcdn.com/120x90/cz.png"}, name: "Czechia"},
   de: {url: {small: "https://flagcdn.com/64x48/de.png", large: "https://flagcdn.com/120x90/de.png"}, name: "Germany"},
   dj: {url: {small: "https://flagcdn.com/64x48/dj.png", large: "https://flagcdn.com/120x90/dj.png"}, name: "Djibouti"},
   dk: {url: {small: "https://flagcdn.com/64x48/dk.png", large: "https://flagcdn.com/120x90/dk.png"}, name: "Denmark"},
   dm: {url: {small: "https://flagcdn.com/64x48/dm.png", large: "https://flagcdn.com/120x90/dm.png"}, name: "Dominica"},
   do: {url: {small: "https://flagcdn.com/64x48/do.png", large: "https://flagcdn.com/120x90/do.png"}, name: "Dominican Republic"},
   dz: {url: {small: "https://flagcdn.com/64x48/dz.png", large: "https://flagcdn.com/120x90/dz.png"}, name: "Algeria"},
   ec: {url: {small: "https://flagcdn.com/64x48/ec.png", large: "https://flagcdn.com/120x90/ec.png"}, name: "Ecuador"},
   ee: {url: {small: "https://flagcdn.com/64x48/ee.png", large: "https://flagcdn.com/120x90/ee.png"}, name: "Estonia"},
   eg: {url: {small: "https://flagcdn.com/64x48/eg.png", large: "https://flagcdn.com/120x90/eg.png"}, name: "Egypt"},
   eh: {url: {small: "https://flagcdn.com/64x48/eh.png", large: "https://flagcdn.com/120x90/eh.png"}, name: "Western Sahara"},
   er: {url: {small: "https://flagcdn.com/64x48/er.png", large: "https://flagcdn.com/120x90/er.png"}, name: "Eritrea"},
   es: {url: {small: "https://flagcdn.com/64x48/es.png", large: "https://flagcdn.com/120x90/es.png"}, name: "Spain"},
   et: {url: {small: "https://flagcdn.com/64x48/et.png", large: "https://flagcdn.com/120x90/et.png"}, name: "Ethiopia"},
   eu: {url: {small: "https://flagcdn.com/64x48/eu.png", large: "https://flagcdn.com/120x90/eu.png"}, name: "European Union"},
   fi: {url: {small: "https://flagcdn.com/64x48/fi.png", large: "https://flagcdn.com/120x90/fi.png"}, name: "Finland"},
   fj: {url: {small: "https://flagcdn.com/64x48/fj.png", large: "https://flagcdn.com/120x90/fj.png"}, name: "Fiji"},
   fk: {url: {small: "https://flagcdn.com/64x48/fk.png", large: "https://flagcdn.com/120x90/fk.png"}, name: "Falkland Islands"},
   fm: {url: {small: "https://flagcdn.com/64x48/fm.png", large: "https://flagcdn.com/120x90/fm.png"}, name: "Micronesia"},
   fo: {url: {small: "https://flagcdn.com/64x48/fo.png", large: "https://flagcdn.com/120x90/fo.png"}, name: "Faroe Islands"},
   fr: {url: {small: "https://flagcdn.com/64x48/fr.png", large: "https://flagcdn.com/120x90/fr.png"}, name: "France"},
   ga: {url: {small: "https://flagcdn.com/64x48/ga.png", large: "https://flagcdn.com/120x90/ga.png"}, name: "Gabon"},
   gb: {url: {small: "https://flagcdn.com/64x48/gb.png", large: "https://flagcdn.com/120x90/gb.png"}, name: "United Kingdom"},
   gd: {url: {small: "https://flagcdn.com/64x48/gd.png", large: "https://flagcdn.com/120x90/gd.png"}, name: "Grenada"},
   ge: {url: {small: "https://flagcdn.com/64x48/ge.png", large: "https://flagcdn.com/120x90/ge.png"}, name: "Georgia"},
   gf: {url: {small: "https://flagcdn.com/64x48/gf.png", large: "https://flagcdn.com/120x90/gf.png"}, name: "French Guiana"},
   gg: {url: {small: "https://flagcdn.com/64x48/gg.png", large: "https://flagcdn.com/120x90/gg.png"}, name: "Guernsey"},
   gh: {url: {small: "https://flagcdn.com/64x48/gh.png", large: "https://flagcdn.com/120x90/gh.png"}, name: "Ghana"},
   gi: {url: {small: "https://flagcdn.com/64x48/gi.png", large: "https://flagcdn.com/120x90/gi.png"}, name: "Gibraltar"},
   gl: {url: {small: "https://flagcdn.com/64x48/gl.png", large: "https://flagcdn.com/120x90/gl.png"}, name: "Greenland"},
   gm: {url: {small: "https://flagcdn.com/64x48/gm.png", large: "https://flagcdn.com/120x90/gm.png"}, name: "Gambia"},
   gn: {url: {small: "https://flagcdn.com/64x48/gn.png", large: "https://flagcdn.com/120x90/gn.png"}, name: "Guinea"},
   gp: {url: {small: "https://flagcdn.com/64x48/gp.png", large: "https://flagcdn.com/120x90/gp.png"}, name: "Guadeloupe"},
   gq: {url: {small: "https://flagcdn.com/64x48/gq.png", large: "https://flagcdn.com/120x90/gq.png"}, name: "Equatorial Guinea"},
   gr: {url: {small: "https://flagcdn.com/64x48/gr.png", large: "https://flagcdn.com/120x90/gr.png"}, name: "Greece"},
   gs: {url: {small: "https://flagcdn.com/64x48/gs.png", large: "https://flagcdn.com/120x90/gs.png"}, name: "South Georgia"},
   gt: {url: {small: "https://flagcdn.com/64x48/gt.png", large: "https://flagcdn.com/120x90/gt.png"}, name: "Guatemala"},
   gu: {url: {small: "https://flagcdn.com/64x48/gu.png", large: "https://flagcdn.com/120x90/gu.png"}, name: "Guam"},
   gw: {url: {small: "https://flagcdn.com/64x48/gw.png", large: "https://flagcdn.com/120x90/gw.png"}, name: "Guinea-Bissau"},
   gy: {url: {small: "https://flagcdn.com/64x48/gy.png", large: "https://flagcdn.com/120x90/gy.png"}, name: "Guyana"},
   hk: {url: {small: "https://flagcdn.com/64x48/hk.png", large: "https://flagcdn.com/120x90/hk.png"}, name: "Hong Kong"},
   hm: {url: {small: "https://flagcdn.com/64x48/hm.png", large: "https://flagcdn.com/120x90/hm.png"}, name: "Heard Island and McDonald Islands"},
   hn: {url: {small: "https://flagcdn.com/64x48/hn.png", large: "https://flagcdn.com/120x90/hn.png"}, name: "Honduras"},
   hr: {url: {small: "https://flagcdn.com/64x48/hr.png", large: "https://flagcdn.com/120x90/hr.png"}, name: "Croatia"},
   ht: {url: {small: "https://flagcdn.com/64x48/ht.png", large: "https://flagcdn.com/120x90/ht.png"}, name: "Haiti"},
   hu: {url: {small: "https://flagcdn.com/64x48/hu.png", large: "https://flagcdn.com/120x90/hu.png"}, name: "Hungary"},
   id: {url: {small: "https://flagcdn.com/64x48/id.png", large: "https://flagcdn.com/120x90/id.png"}, name: "Indonesia"},
   ie: {url: {small: "https://flagcdn.com/64x48/ie.png", large: "https://flagcdn.com/120x90/ie.png"}, name: "Ireland"},
   il: {url: {small: "https://flagcdn.com/64x48/il.png", large: "https://flagcdn.com/120x90/il.png"}, name: "Israel"},
   im: {url: {small: "https://flagcdn.com/64x48/im.png", large: "https://flagcdn.com/120x90/im.png"}, name: "Isle of Man"},
   in: {url: {small: "https://flagcdn.com/64x48/in.png", large: "https://flagcdn.com/120x90/in.png"}, name: "India"},
   io: {url: {small: "https://flagcdn.com/64x48/io.png", large: "https://flagcdn.com/120x90/io.png"}, name: "British Indian Ocean Territory"},
   iq: {url: {small: "https://flagcdn.com/64x48/iq.png", large: "https://flagcdn.com/120x90/iq.png"}, name: "Iraq"},
   ir: {url: {small: "https://flagcdn.com/64x48/ir.png", large: "https://flagcdn.com/120x90/ir.png"}, name: "Iran"},
   is: {url: {small: "https://flagcdn.com/64x48/is.png", large: "https://flagcdn.com/120x90/is.png"}, name: "Iceland"},
   it: {url: {small: "https://flagcdn.com/64x48/it.png", large: "https://flagcdn.com/120x90/it.png"}, name: "Italy"},
   je: {url: {small: "https://flagcdn.com/64x48/je.png", large: "https://flagcdn.com/120x90/je.png"}, name: "Jersey"},
   jm: {url: {small: "https://flagcdn.com/64x48/jm.png", large: "https://flagcdn.com/120x90/jm.png"}, name: "Jamaica"},
   jo: {url: {small: "https://flagcdn.com/64x48/jo.png", large: "https://flagcdn.com/120x90/jo.png"}, name: "Jordan"},
   jp: {url: {small: "https://flagcdn.com/64x48/jp.png", large: "https://flagcdn.com/120x90/jp.png"}, name: "Japan"},
   ke: {url: {small: "https://flagcdn.com/64x48/ke.png", large: "https://flagcdn.com/120x90/ke.png"}, name: "Kenya"},
   kg: {url: {small: "https://flagcdn.com/64x48/kg.png", large: "https://flagcdn.com/120x90/kg.png"}, name: "Kyrgyzstan"},
   kh: {url: {small: "https://flagcdn.com/64x48/kh.png", large: "https://flagcdn.com/120x90/kh.png"}, name: "Cambodia"},
   ki: {url: {small: "https://flagcdn.com/64x48/ki.png", large: "https://flagcdn.com/120x90/ki.png"}, name: "Kiribati"},
   km: {url: {small: "https://flagcdn.com/64x48/km.png", large: "https://flagcdn.com/120x90/km.png"}, name: "Comoros"},
   kn: {url: {small: "https://flagcdn.com/64x48/kn.png", large: "https://flagcdn.com/120x90/kn.png"}, name: "Saint Kitts and Nevis"},
   kp: {url: {small: "https://flagcdn.com/64x48/kp.png", large: "https://flagcdn.com/120x90/kp.png"}, name: "North Korea"},
   kr: {url: {small: "https://flagcdn.com/64x48/kr.png", large: "https://flagcdn.com/120x90/kr.png"}, name: "South Korea"},
   kw: {url: {small: "https://flagcdn.com/64x48/kw.png", large: "https://flagcdn.com/120x90/kw.png"}, name: "Kuwait"},
   ky: {url: {small: "https://flagcdn.com/64x48/ky.png", large: "https://flagcdn.com/120x90/ky.png"}, name: "Cayman Islands"},
   kz: {url: {small: "https://flagcdn.com/64x48/kz.png", large: "https://flagcdn.com/120x90/kz.png"}, name: "Kazakhstan"},
   la: {url: {small: "https://flagcdn.com/64x48/la.png", large: "https://flagcdn.com/120x90/la.png"}, name: "Laos"},
   lb: {url: {small: "https://flagcdn.com/64x48/lb.png", large: "https://flagcdn.com/120x90/lb.png"}, name: "Lebanon"},
   lc: {url: {small: "https://flagcdn.com/64x48/lc.png", large: "https://flagcdn.com/120x90/lc.png"}, name: "Saint Lucia"},
   li: {url: {small: "https://flagcdn.com/64x48/li.png", large: "https://flagcdn.com/120x90/li.png"}, name: "Liechtenstein"},
   lk: {url: {small: "https://flagcdn.com/64x48/lk.png", large: "https://flagcdn.com/120x90/lk.png"}, name: "Sri Lanka"},
   lr: {url: {small: "https://flagcdn.com/64x48/lr.png", large: "https://flagcdn.com/120x90/lr.png"}, name: "Liberia"},
   ls: {url: {small: "https://flagcdn.com/64x48/ls.png", large: "https://flagcdn.com/120x90/ls.png"}, name: "Lesotho"},
   lt: {url: {small: "https://flagcdn.com/64x48/lt.png", large: "https://flagcdn.com/120x90/lt.png"}, name: "Lithuania"},
   lu: {url: {small: "https://flagcdn.com/64x48/lu.png", large: "https://flagcdn.com/120x90/lu.png"}, name: "Luxembourg"},
   lv: {url: {small: "https://flagcdn.com/64x48/lv.png", large: "https://flagcdn.com/120x90/lv.png"}, name: "Latvia"},
   ly: {url: {small: "https://flagcdn.com/64x48/ly.png", large: "https://flagcdn.com/120x90/ly.png"}, name: "Libya"},
   ma: {url: {small: "https://flagcdn.com/64x48/ma.png", large: "https://flagcdn.com/120x90/ma.png"}, name: "Morocco"},
   mc: {url: {small: "https://flagcdn.com/64x48/mc.png", large: "https://flagcdn.com/120x90/mc.png"}, name: "Monaco"},
   md: {url: {small: "https://flagcdn.com/64x48/md.png", large: "https://flagcdn.com/120x90/md.png"}, name: "Moldova"},
   me: {url: {small: "https://flagcdn.com/64x48/me.png", large: "https://flagcdn.com/120x90/me.png"}, name: "Montenegro"},
   mf: {url: {small: "https://flagcdn.com/64x48/mf.png", large: "https://flagcdn.com/120x90/mf.png"}, name: "Saint Martin"},
   mg: {url: {small: "https://flagcdn.com/64x48/mg.png", large: "https://flagcdn.com/120x90/mg.png"}, name: "Madagascar"},
   mh: {url: {small: "https://flagcdn.com/64x48/mh.png", large: "https://flagcdn.com/120x90/mh.png"}, name: "Marshall Islands"},
   mk: {url: {small: "https://flagcdn.com/64x48/mk.png", large: "https://flagcdn.com/120x90/mk.png"}, name: "North Macedonia"},
   ml: {url: {small: "https://flagcdn.com/64x48/ml.png", large: "https://flagcdn.com/120x90/ml.png"}, name: "Mali"},
   mm: {url: {small: "https://flagcdn.com/64x48/mm.png", large: "https://flagcdn.com/120x90/mm.png"}, name: "Myanmar"},
   mn: {url: {small: "https://flagcdn.com/64x48/mn.png", large: "https://flagcdn.com/120x90/mn.png"}, name: "Mongolia"},
   mo: {url: {small: "https://flagcdn.com/64x48/mo.png", large: "https://flagcdn.com/120x90/mo.png"}, name: "Macau"},
   mp: {url: {small: "https://flagcdn.com/64x48/mp.png", large: "https://flagcdn.com/120x90/mp.png"}, name: "Northern Mariana Islands"},
   mq: {url: {small: "https://flagcdn.com/64x48/mq.png", large: "https://flagcdn.com/120x90/mq.png"}, name: "Martinique"},
   mr: {url: {small: "https://flagcdn.com/64x48/mr.png", large: "https://flagcdn.com/120x90/mr.png"}, name: "Mauritania"},
   ms: {url: {small: "https://flagcdn.com/64x48/ms.png", large: "https://flagcdn.com/120x90/ms.png"}, name: "Montserrat"},
   mt: {url: {small: "https://flagcdn.com/64x48/mt.png", large: "https://flagcdn.com/120x90/mt.png"}, name: "Malta"},
   mu: {url: {small: "https://flagcdn.com/64x48/mu.png", large: "https://flagcdn.com/120x90/mu.png"}, name: "Mauritius"},
   mv: {url: {small: "https://flagcdn.com/64x48/mv.png", large: "https://flagcdn.com/120x90/mv.png"}, name: "Maldives"},
   mw: {url: {small: "https://flagcdn.com/64x48/mw.png", large: "https://flagcdn.com/120x90/mw.png"}, name: "Malawi"},
   mx: {url: {small: "https://flagcdn.com/64x48/mx.png", large: "https://flagcdn.com/120x90/mx.png"}, name: "Mexico"},
   my: {url: {small: "https://flagcdn.com/64x48/my.png", large: "https://flagcdn.com/120x90/my.png"}, name: "Malaysia"},
   mz: {url: {small: "https://flagcdn.com/64x48/mz.png", large: "https://flagcdn.com/120x90/mz.png"}, name: "Mozambique"},
   na: {url: {small: "https://flagcdn.com/64x48/na.png", large: "https://flagcdn.com/120x90/na.png"}, name: "Namibia"},
   nc: {url: {small: "https://flagcdn.com/64x48/nc.png", large: "https://flagcdn.com/120x90/nc.png"}, name: "New Caledonia"},
   ne: {url: {small: "https://flagcdn.com/64x48/ne.png", large: "https://flagcdn.com/120x90/ne.png"}, name: "Niger"},
   nf: {url: {small: "https://flagcdn.com/64x48/nf.png", large: "https://flagcdn.com/120x90/nf.png"}, name: "Norfolk Island"},
   ng: {url: {small: "https://flagcdn.com/64x48/ng.png", large: "https://flagcdn.com/120x90/ng.png"}, name: "Nigeria"},
   ni: {url: {small: "https://flagcdn.com/64x48/ni.png", large: "https://flagcdn.com/120x90/ni.png"}, name: "Nicaragua"},
   nl: {url: {small: "https://flagcdn.com/64x48/nl.png", large: "https://flagcdn.com/120x90/nl.png"}, name: "Netherlands"},
   no: {url: {small: "https://flagcdn.com/64x48/no.png", large: "https://flagcdn.com/120x90/no.png"}, name: "Norway"},
   np: {url: {small: "https://flagcdn.com/64x48/np.png", large: "https://flagcdn.com/120x90/np.png"}, name: "Nepal"},
   nr: {url: {small: "https://flagcdn.com/64x48/nr.png", large: "https://flagcdn.com/120x90/nr.png"}, name: "Nauru"},
   nu: {url: {small: "https://flagcdn.com/64x48/nu.png", large: "https://flagcdn.com/120x90/nu.png"}, name: "Niue"},
   nz: {url: {small: "https://flagcdn.com/64x48/nz.png", large: "https://flagcdn.com/120x90/nz.png"}, name: "New Zealand"},
   om: {url: {small: "https://flagcdn.com/64x48/om.png", large: "https://flagcdn.com/120x90/om.png"}, name: "Oman"},
   pa: {url: {small: "https://flagcdn.com/64x48/pa.png", large: "https://flagcdn.com/120x90/pa.png"}, name: "Panama"},
   pe: {url: {small: "https://flagcdn.com/64x48/pe.png", large: "https://flagcdn.com/120x90/pe.png"}, name: "Peru"},
   pf: {url: {small: "https://flagcdn.com/64x48/pf.png", large: "https://flagcdn.com/120x90/pf.png"}, name: "French Polynesia"},
   pg: {url: {small: "https://flagcdn.com/64x48/pg.png", large: "https://flagcdn.com/120x90/pg.png"}, name: "Papua New Guinea"},
   ph: {url: {small: "https://flagcdn.com/64x48/ph.png", large: "https://flagcdn.com/120x90/ph.png"}, name: "Philippines"},
   pk: {url: {small: "https://flagcdn.com/64x48/pk.png", large: "https://flagcdn.com/120x90/pk.png"}, name: "Pakistan"},
   pl: {url: {small: "https://flagcdn.com/64x48/pl.png", large: "https://flagcdn.com/120x90/pl.png"}, name: "Poland"},
   pm: {url: {small: "https://flagcdn.com/64x48/pm.png", large: "https://flagcdn.com/120x90/pm.png"}, name: "Saint Pierre and Miquelon"},
   pn: {url: {small: "https://flagcdn.com/64x48/pn.png", large: "https://flagcdn.com/120x90/pn.png"}, name: "Pitcairn Islands"},
   pr: {url: {small: "https://flagcdn.com/64x48/pr.png", large: "https://flagcdn.com/120x90/pr.png"}, name: "Puerto Rico"},
   ps: {url: {small: "https://flagcdn.com/64x48/ps.png", large: "https://flagcdn.com/120x90/ps.png"}, name: "Palestine"},
   pt: {url: {small: "https://flagcdn.com/64x48/pt.png", large: "https://flagcdn.com/120x90/pt.png"}, name: "Portugal"},
   pw: {url: {small: "https://flagcdn.com/64x48/pw.png", large: "https://flagcdn.com/120x90/pw.png"}, name: "Palau"},
   py: {url: {small: "https://flagcdn.com/64x48/py.png", large: "https://flagcdn.com/120x90/py.png"}, name: "Paraguay"},
   qa: {url: {small: "https://flagcdn.com/64x48/qa.png", large: "https://flagcdn.com/120x90/qa.png"}, name: "Qatar"},
   re: {url: {small: "https://flagcdn.com/64x48/re.png", large: "https://flagcdn.com/120x90/re.png"}, name: "Réunion"},
   ro: {url: {small: "https://flagcdn.com/64x48/ro.png", large: "https://flagcdn.com/120x90/ro.png"}, name: "Romania"},
   rs: {url: {small: "https://flagcdn.com/64x48/rs.png", large: "https://flagcdn.com/120x90/rs.png"}, name: "Serbia"},
   ru: {url: {small: "https://flagcdn.com/64x48/ru.png", large: "https://flagcdn.com/120x90/ru.png"}, name: "Russia"},
   rw: {url: {small: "https://flagcdn.com/64x48/rw.png", large: "https://flagcdn.com/120x90/rw.png"}, name: "Rwanda"},
   sa: {url: {small: "https://flagcdn.com/64x48/sa.png", large: "https://flagcdn.com/120x90/sa.png"}, name: "Saudi Arabia"},
   sb: {url: {small: "https://flagcdn.com/64x48/sb.png", large: "https://flagcdn.com/120x90/sb.png"}, name: "Solomon Islands"},
   sc: {url: {small: "https://flagcdn.com/64x48/sc.png", large: "https://flagcdn.com/120x90/sc.png"}, name: "Seychelles"},
   sd: {url: {small: "https://flagcdn.com/64x48/sd.png", large: "https://flagcdn.com/120x90/sd.png"}, name: "Sudan"},
   se: {url: {small: "https://flagcdn.com/64x48/se.png", large: "https://flagcdn.com/120x90/se.png"}, name: "Sweden"},
   sg: {url: {small: "https://flagcdn.com/64x48/sg.png", large: "https://flagcdn.com/120x90/sg.png"}, name: "Singapore"},
   sh: {url: {small: "https://flagcdn.com/64x48/sh.png", large: "https://flagcdn.com/120x90/sh.png"}, name: "Saint Helena, Ascension and Tristan da Cunha"},
   si: {url: {small: "https://flagcdn.com/64x48/si.png", large: "https://flagcdn.com/120x90/si.png"}, name: "Slovenia"},
   sj: {url: {small: "https://flagcdn.com/64x48/sj.png", large: "https://flagcdn.com/120x90/sj.png"}, name: "Svalbard and Jan Mayen"},
   sk: {url: {small: "https://flagcdn.com/64x48/sk.png", large: "https://flagcdn.com/120x90/sk.png"}, name: "Slovakia"},
   sl: {url: {small: "https://flagcdn.com/64x48/sl.png", large: "https://flagcdn.com/120x90/sl.png"}, name: "Sierra Leone"},
   sm: {url: {small: "https://flagcdn.com/64x48/sm.png", large: "https://flagcdn.com/120x90/sm.png"}, name: "San Marino"},
   sn: {url: {small: "https://flagcdn.com/64x48/sn.png", large: "https://flagcdn.com/120x90/sn.png"}, name: "Senegal"},
   so: {url: {small: "https://flagcdn.com/64x48/so.png", large: "https://flagcdn.com/120x90/so.png"}, name: "Somalia"},
   sr: {url: {small: "https://flagcdn.com/64x48/sr.png", large: "https://flagcdn.com/120x90/sr.png"}, name: "Suriname"},
   ss: {url: {small: "https://flagcdn.com/64x48/ss.png", large: "https://flagcdn.com/120x90/ss.png"}, name: "South Sudan"},
   st: {url: {small: "https://flagcdn.com/64x48/st.png", large: "https://flagcdn.com/120x90/st.png"}, name: "São Tomé and Príncipe"},
   sv: {url: {small: "https://flagcdn.com/64x48/sv.png", large: "https://flagcdn.com/120x90/sv.png"}, name: "El Salvador"},
   sx: {url: {small: "https://flagcdn.com/64x48/sx.png", large: "https://flagcdn.com/120x90/sx.png"}, name: "Sint Maarten"},
   sy: {url: {small: "https://flagcdn.com/64x48/sy.png", large: "https://flagcdn.com/120x90/sy.png"}, name: "Syria"},
   sz: {url: {small: "https://flagcdn.com/64x48/sz.png", large: "https://flagcdn.com/120x90/sz.png"}, name: "Eswatini (Swaziland)"},
   tc: {url: {small: "https://flagcdn.com/64x48/tc.png", large: "https://flagcdn.com/120x90/tc.png"}, name: "Turks and Caicos Islands"},
   td: {url: {small: "https://flagcdn.com/64x48/td.png", large: "https://flagcdn.com/120x90/td.png"}, name: "Chad"},
   tf: {url: {small: "https://flagcdn.com/64x48/tf.png", large: "https://flagcdn.com/120x90/tf.png"}, name: "French Southern and Antarctic Lands"},
   tg: {url: {small: "https://flagcdn.com/64x48/tg.png", large: "https://flagcdn.com/120x90/tg.png"}, name: "Togo"},
   th: {url: {small: "https://flagcdn.com/64x48/th.png", large: "https://flagcdn.com/120x90/th.png"}, name: "Thailand"},
   tj: {url: {small: "https://flagcdn.com/64x48/tj.png", large: "https://flagcdn.com/120x90/tj.png"}, name: "Tajikistan"},
   tk: {url: {small: "https://flagcdn.com/64x48/tk.png", large: "https://flagcdn.com/120x90/tk.png"}, name: "Tokelau"},
   tl: {url: {small: "https://flagcdn.com/64x48/tl.png", large: "https://flagcdn.com/120x90/tl.png"}, name: "Timor-Leste"},
   tm: {url: {small: "https://flagcdn.com/64x48/tm.png", large: "https://flagcdn.com/120x90/tm.png"}, name: "Turkmenistan"},
   tn: {url: {small: "https://flagcdn.com/64x48/tn.png", large: "https://flagcdn.com/120x90/tn.png"}, name: "Tunisia"},
   to: {url: {small: "https://flagcdn.com/64x48/to.png", large: "https://flagcdn.com/120x90/to.png"}, name: "Tonga"},
   tr: {url: {small: "https://flagcdn.com/64x48/tr.png", large: "https://flagcdn.com/120x90/tr.png"}, name: "Turkey"},
   tt: {url: {small: "https://flagcdn.com/64x48/tt.png", large: "https://flagcdn.com/120x90/tt.png"}, name: "Trinidad and Tobago"},
   tv: {url: {small: "https://flagcdn.com/64x48/tv.png", large: "https://flagcdn.com/120x90/tv.png"}, name: "Tuvalu"},
   tw: {url: {small: "https://flagcdn.com/64x48/tw.png", large: "https://flagcdn.com/120x90/tw.png"}, name: "Taiwan"},
   tz: {url: {small: "https://flagcdn.com/64x48/tz.png", large: "https://flagcdn.com/120x90/tz.png"}, name: "Tanzania"},
   ua: {url: {small: "https://flagcdn.com/64x48/ua.png", large: "https://flagcdn.com/120x90/ua.png"}, name: "Ukraine"},
   ug: {url: {small: "https://flagcdn.com/64x48/ug.png", large: "https://flagcdn.com/120x90/ug.png"}, name: "Uganda"},
   um: {url: {small: "https://flagcdn.com/64x48/um.png", large: "https://flagcdn.com/120x90/um.png"}, name: "United States Minor Outlying Islands"},
   un: {url: {small: "https://flagcdn.com/64x48/un.png", large: "https://flagcdn.com/120x90/un.png"}, name: "United Nations"},
   us: {url: {small: "https://flagcdn.com/64x48/us.png", large: "https://flagcdn.com/120x90/us.png"}, name: "United States"},
   uy: {url: {small: "https://flagcdn.com/64x48/uy.png", large: "https://flagcdn.com/120x90/uy.png"}, name: "Uruguay"},
   uz: {url: {small: "https://flagcdn.com/64x48/uz.png", large: "https://flagcdn.com/120x90/uz.png"}, name: "Uzbekistan"},
   va: {url: {small: "https://flagcdn.com/64x48/va.png", large: "https://flagcdn.com/120x90/va.png"}, name: "Vatican City (Holy See)"},
   vc: {url: {small: "https://flagcdn.com/64x48/vc.png", large: "https://flagcdn.com/120x90/vc.png"}, name: "Saint Vincent and the Grenadines"},
   ve: {url: {small: "https://flagcdn.com/64x48/ve.png", large: "https://flagcdn.com/120x90/ve.png"}, name: "Venezuela"},
   vg: {url: {small: "https://flagcdn.com/64x48/vg.png", large: "https://flagcdn.com/120x90/vg.png"}, name: "British Virgin Islands"},
   vi: {url: {small: "https://flagcdn.com/64x48/vi.png", large: "https://flagcdn.com/120x90/vi.png"}, name: "United States Virgin Islands"},
   vn: {url: {small: "https://flagcdn.com/64x48/vn.png", large: "https://flagcdn.com/120x90/vn.png"}, name: "Vietnam"},
   vu: {url: {small: "https://flagcdn.com/64x48/vu.png", large: "https://flagcdn.com/120x90/vu.png"}, name: "Vanuatu"},
   wf: {url: {small: "https://flagcdn.com/64x48/wf.png", large: "https://flagcdn.com/120x90/wf.png"}, name: "Wallis and Futuna"},
   ws: {url: {small: "https://flagcdn.com/64x48/ws.png", large: "https://flagcdn.com/120x90/ws.png"}, name: "Samoa"},
   xk: {url: {small: "https://flagcdn.com/64x48/xk.png", large: "https://flagcdn.com/120x90/xk.png"}, name: "Kosovo"},
   ye: {url: {small: "https://flagcdn.com/64x48/ye.png", large: "https://flagcdn.com/120x90/ye.png"}, name: "Yemen"},
   yt: {url: {small: "https://flagcdn.com/64x48/yt.png", large: "https://flagcdn.com/120x90/yt.png"}, name: "Mayotte"},
   za: {url: {small: "https://flagcdn.com/64x48/za.png", large: "https://flagcdn.com/120x90/za.png"}, name: "South Africa"},
   zm: {url: {small: "https://flagcdn.com/64x48/zm.png", large: "https://flagcdn.com/120x90/zm.png"}, name: "Zambia"},
   zw: {url: {small: "https://flagcdn.com/64x48/zw.png", large: "https://flagcdn.com/120x90/zw.png"}, name: "Zimbabwe"},
};